pull_request_rules:
  # for dependabot
  - name: Auto merge dependabot updates
    conditions:
      - and:
          - author=dependabot[bot]
          - label=dependencies
          - label=github_actions
          - check-success=flake check
          # - check-success=nixosConfig loneros # 有待商榷
    actions:
      update:
      merge:
        method: squash
  # for update flake.lock action
  - name: Auto merge flake.lock updates
    conditions:
      - and:
          - "title~=^Update flake.lock.*"
          - label=auto_update_flake
          - label=github_actions
          - check-success=flake check
          - check-success=build nixos & push to cachix
    actions:
      merge:
        method: squash
  # for auto update custom package
  - name: Auto merge custom package updates
    conditions:
      - "title~=^Chore: auto update custom package.*"
      - label=auto_update_custom_package
      - label=github_actions
      - check-success=flake check
    actions:
      merge:
        method: squash
