# Automatically merge PRs with dependency upgrades
pull_request_rules:
  - name: Merge when labeled and all CI jobs pass
    conditions:
      - and:
          - label=dependencies
          - check-success=flake check
          # - check-success=nixosConfig loneros # 有待商榷
    actions:
      update:
      merge:
        method: squash
