name: flake check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: flake check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            accept-flake-config = true

      - name: Add Cachix
        uses: cachix/cachix-action@v14
        with:
          name: loneros
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check
        run: |
          nix flake check --all-systems
