name: Sync Nixpkgs Fork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

concurrency:
  group: sync-nixpkgs
  cancel-in-progress: true

jobs:
  sync:
    name: Remote Sync
    runs-on: ubuntu-latest
    steps:
      - name: Sync via GitHub API
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh repo sync lonerOrz/nixpkgs \
            --source NixOS/nixpkgs \
            --branch master \
            --force
